In [1]:
import numpy as np

In [2]:
x = np.array([56,22,12,67,89,53])

In [3]:
x

array([56, 22, 12, 67, 89, 53])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.dtype

dtype('int64')

In [6]:
x.size

6

In [7]:
x[3]

67

In [8]:
y = np.array([56,22,12.23,67,89,53])

In [9]:
y

array([56.  , 22.  , 12.23, 67.  , 89.  , 53.  ])

In [10]:
y.dtype

dtype('float64')

In [11]:
y[1]

22.0

In [16]:
city = np.array(['पुणे', 'नागपुर', 'नाशिक', 'सातारा'])

In [17]:
city

array(['पुणे', 'नागपुर', 'नाशिक', 'सातारा'], dtype='<U6')

In [18]:
city.dtype

dtype('<U6')

In [19]:
city[3]

'सातारा'

In [20]:
type(city[3])

numpy.str_

In [21]:
z = np.array([[5,6,7],[3,5,6],[1,0,9],[4,8,1]])

In [22]:
z

array([[5, 6, 7],
       [3, 5, 6],
       [1, 0, 9],
       [4, 8, 1]])

In [23]:
z.shape

(4, 3)

In [24]:
z.dtype

dtype('int64')

In [25]:
z.max()

9

In [26]:
z.mean()

4.583333333333333